{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gnis.fullname" . }}
  labels:
    {{- include "gnis.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
  volumeMode: Filesystem
  {{- if .Values.persistence.pv.enabled }}
  volumeName: {{ include "gnis.fullname" . }}-pv
  {{- end }}
{{- end }}
