apiVersion: v1
kind: Service
metadata:
  name: {{ include "gnis.fullname" . }}
  labels:
    {{- include "gnis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: gnis
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "gnis.selectorLabels" . | nindent 4 }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if eq .Values.service.sessionAffinity "ClientIP" }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinityTimeoutSeconds }}
  {{- end }}
